const id = (path: string) => (entityId: string): string => `${path}/${entityId}`

const lifecycle = (base: string) => ({
  trashed: `${base}/trashed`,
  softDelete: (entityId: string) => `${base}/${entityId}/soft-delete`,
  restore: (entityId: string) => `${base}/${entityId}/restore`,
})

export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    csrf: '/auth/csrf',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    me: '/auth/me',
    changePassword: '/auth/change-password',
  },
  users: {
    list: '/users',
    byId: id('/users'),
    profile: (userId: string) => `/users/${userId}/profile`,
    search: '/users/search',
    searchTrashed: '/users/trashed/search',
    active: '/users/active',
    inactive: '/users/inactive',
    deactivate: (userId: string) => `/users/${userId}/deactivate`,
    reactivate: (userId: string) => `/users/${userId}/reactivate`,
    ...lifecycle('/users'),
  },
  subscriptions: {
    plans: '/subscriptions/plans',
    list: '/subscriptions',
    byId: id('/subscriptions'),
    profile: (subscriptionId: string) => `/subscriptions/${subscriptionId}/profile`,
    search: '/subscriptions/search',
    searchTrashed: '/subscriptions/trashed/search',
    active: '/subscriptions/active',
    inactive: '/subscriptions/inactive',
    deactivate: (subscriptionId: string) => `/subscriptions/${subscriptionId}/deactivate`,
    reactivate: (subscriptionId: string) => `/subscriptions/${subscriptionId}/reactivate`,
    ...lifecycle('/subscriptions'),
  },
  billing: {
    list: '/billing/invoices',
    byId: id('/billing/invoices'),
    //plans: '/billing/plans', moved to subscriptions
    subscription: '/billing/subscription',
    subscribe: '/billing/subscribe',
    cancel: '/billing/cancel',
    invoices: '/billing/invoices',
    paymentMethods: '/billing/payment-methods',
    paymentConfig: '/billing/payment-config',
    stripeCreateIntent: '/billing/stripe/create-intent',
    twoCTwoPToken: '/billing/2c2p/payment-token',
    twoCTwoPProcess: '/billing/2c2p/process',
    checkout: '/billing/checkout',
    ...lifecycle('/billing/invoices'),
  },
  employees: {
    list: '/employees',
    byId: id('/employees'),
    employmentHistory: (employeeId: string) => `/employees/${employeeId}/employment-history`,
    promote: (employeeId: string) => `/employees/${employeeId}/promote`,
    transfer: (employeeId: string) => `/employees/${employeeId}/transfer`,
    search: '/employees/search',
    searchTrashed: '/employees/trashed/search',
    byDepartment: (departmentId: string) => `/employees/by-department/${departmentId}`,
    byManager: (managerId: string) => `/employees/by-manager/${managerId}`,
    active: '/employees/active',
    resigned: '/employees/resigned',
    deactivate: (employeeId: string) => `/employees/${employeeId}/deactivate`,
    ...lifecycle('/employees'),
  },
  employeeDepartments: {
    list: '/employee-departments',
    byId: id('/employee-departments'),
    ...lifecycle('/employee-departments'),
  },
  departments: {
    list: '/departments',
    byId: id('/departments'),
    employees: (d: string) => `/departments/${d}/employees`,
    ...lifecycle('/departments'),
  },
  positions: {
    list: '/positions',
    byId: id('/positions'),
    ...lifecycle('/positions'),
  },
  attendance: {
    checkIn: '/attendance/check-in',
    checkOut: '/attendance/check-out',
    list: '/attendance',
    byId: id('/attendance'),
    byEmployee: (e: string) => `/attendance/${e}`,
    today: '/attendance/today',
    range: '/attendance/range',
    summary: (e: string) => `/attendance/summary/${e}`,
    ...lifecycle('/attendance'),
  },
  leave: {
    list: '/leaves',
    apply: '/leaves/apply',
    byId: id('/leaves'),
    approve: (l: string) => `/leaves/${l}/approve`,
    reject: (l: string) => `/leaves/${l}/reject`,
    cancel: (l: string) => `/leaves/${l}/cancel`,
    balance: (e: string) => `/leaves/balance/${e}`,
    pending: '/leaves/pending',
    history: (e: string) => `/leaves/history/${e}`,
    ...lifecycle('/leaves'),
  },
  payroll: {
    list: '/payroll',
    byId: id('/payroll'),
    generate: '/payroll/generate',
    run: '/payroll/run',
    slips: (e: string) => `/payroll/slips/${e}`,
    summary: '/payroll/summary',
    history: '/payroll/history',
    ...lifecycle('/payroll'),
  },
  compensation: {
    list: '/compensation',
    byId: id('/compensation'),
    byEmployee: (e: string) => `/compensation/${e}`,
    adjust: (e: string) => `/compensation/${e}/adjust`,
    salaryStructures: '/salary-structures',
    ...lifecycle('/compensation'),
  },
  timeTracking: {
    list: '/time-logs',
    byId: id('/time-logs'),
    start: '/time-logs/start',
    stop: '/time-logs/stop',
    byEmployee: (e: string) => `/time-logs/${e}`,
    today: (e: string) => `/time-logs/today/${e}`,
    ...lifecycle('/time-logs'),
  },
  recruitment: {
    list: '/recruitment/jobs',
    byId: id('/recruitment/jobs'),
    jobs: '/recruitment/jobs',
    job: id('/recruitment/jobs'),
    applicants: '/recruitment/applicants',
    applicant: id('/recruitment/applicants'),
    scheduleInterview: (a: string) => `/recruitment/applicants/${a}/schedule-interview`,
    hire: (a: string) => `/recruitment/applicants/${a}/hire`,
    reject: (a: string) => `/recruitment/applicants/${a}/reject`,
    ...lifecycle('/recruitment/jobs'),
    applicantsTrashed: '/recruitment/applicants/trashed',
    applicantsSoftDelete: (a: string) => `/recruitment/applicants/${a}/soft-delete`,
    applicantsRestore: (a: string) => `/recruitment/applicants/${a}/restore`,
  },
  interviews: {
    list: '/interviews',
    byId: id('/interviews'),
    reschedule: (i: string) => `/interviews/${i}/reschedule`,
    complete: (i: string) => `/interviews/${i}/complete`,
    ...lifecycle('/interviews'),
  },
  performance: {
    list: '/performance/reviews',
    byId: id('/performance/reviews'),
    reviews: '/performance/reviews',
    review: id('/performance/reviews'),
    submit: (r: string) => `/performance/reviews/${r}/submit`,
    approve: (r: string) => `/performance/reviews/${r}/approve`,
    ratings: (e: string) => `/performance/ratings/${e}`,
    ...lifecycle('/performance/reviews'),
  },
  organization: {
    list: '/org/chart',
    byId: (id: string) => `/org/chart/${id}`,
    chart: '/org/chart',
    reportingLines: '/org/reporting-lines',
    positionsTree: '/org/positions-tree',
    ...lifecycle('/org/chart'),
  },
  documents: {
    upload: '/documents/upload',
    list: '/documents',
    byId: id('/documents'),
    byEmployee: (e: string) => `/documents/employee/${e}`,
    ...lifecycle('/documents'),
  },
  notifications: {
    list: '/notifications',
    recent: '/notifications/recent',
    markRead: '/notifications/mark-read',
    markAllRead: '/notifications/mark-all-read',
    byId: id('/notifications'),
    ...lifecycle('/notifications'),
  },
  roles: {
    list: '/roles',
    byId: id('/roles'),
    permissions: '/permissions',
    rolePermissions: (r: string) => `/roles/${r}/permissions`,
    ...lifecycle('/roles'),
  },
  audit: {
    list: '/audit-logs',
    byId: id('/audit-logs'),
    byEntity: (entity: string, entityId: string) => `/audit-logs/${entity}/${entityId}`,
    byUser: (userId: string) => `/audit-logs/user/${userId}`,
  },
  reports: {
    list: '/reports',
    byId: id('/reports'),
    employees: '/reports/employees',
    attendance: '/reports/attendance',
    payroll: '/reports/payroll',
    leaveUsage: '/reports/leave-usage',
    turnover: '/reports/turnover',
  },
  analytics: { dashboard: '/analytics/dashboard' },
  settings: {
    list: '/settings',
    byId: id('/settings'),
    root: '/settings',
    company: '/settings/company',
    leaveTypes: '/settings/leave-types',
    ...lifecycle('/settings'),
  },
  tenants: {
    list: '/tenants',
    byId: id('/tenants'),
    suspend: (t: string) => `/tenants/${t}/suspend`,
    reactivate: (t: string) => `/tenants/${t}/reactivate`,
    ...lifecycle('/tenants'),
  },
  system: {
    list: '/system/health-summary',
    byId: id('/system/health-summary'),
    health: '/health',
    healthSummary: '/system/health-summary',
    metrics: '/metrics',
    status: '/status',
    version: '/version',
  },
  permissions: {
    list: '/permissions',
    assign: (roleId: string) => `/roles/${roleId}/permissions`,
  },
  onboarding: {
    list: '/onboarding',
    byId: id('/onboarding'),
    ...lifecycle('/onboarding'),
  },
  benefits: {
    list: '/benefits',
    byId: id('/benefits'),
    plans: '/benefits/plans',
    enrollments: '/benefits/enrollments',
    ...lifecycle('/benefits'),
  },
  training: {
    list: '/training',
    byId: id('/training'),
    courses: '/training/courses',
    enrollments: '/training/enrollments',
    ...lifecycle('/training'),
  },
  messages: {
    inbox: '/messages/inbox',
  },
} as const
